version: '3'
services:
  db:
    container_name: 'btl-htdttt'
    hostname: 'btl-htdttt'
    image: 'postgres:13.2-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: btl-htdttt
      POSTGRES_USER: btl-htdttt
      POSTGRES_PASSWORD: abcd1234
    volumes:
      - ./db:/var/lib/postgresql/data